#_errors:
#    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
#    prefix: /_error

# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_provider:
    path: /
    controller: App\Controller\ProviderController::provider